name: Bot

on:
  push:
    branches: [ "bot" ]
  pull_request:
    branches: [ "bot" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: cd into EOSC.Bot
      run: cd EOSC.Bot
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.200
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
