name: Build Bot

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.200
    - name: Inject Discord Token
      run: |
        cd EOSC.Bot
        echo "namespace EOSC.Bot;" > secrets.cs
        echo "public static class secrets" >> secrets.cs
        echo "{" >> secrets.cs
        echo "    public static readonly string DiscordToken = \"${{secrets.DISCORD_TOKEN}}\";" >> secrets.cs
        echo "}" >> secrets.cs
    - name: Restore dependencies
      run: |
        cd EOSC.Bot
        dotnet restore
    - name: Build
      run: |
        cd EOSC.Bot
        dotnet build --no-restore
