name: Build api

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_api:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.200
    - name: Restore dependencies
      run: |
        cd EOSC.API
        dotnet restore
    - name: Build
      run: |
        cd EOSC.API
        dotnet build --no-restore
