name: Build Bot

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: cd into EOSC.Bot
      run: cd EOSC.Bot
    - name: Login to dockerhub
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build
      run: |
        docker build --build-arg DISCORD_TOKEN=${{secrets.DISCORD_TOKEN}} -t ${{secrets.DOCKER_USERNAME}}/eoscbot .
        docker push ${{secrets.DOCKER_USERNAME}}/eoscbot:latest
#   deploy: 
#     runs-on: ec2_bot