name: Build Bot

on:
  pull_request:
    types:
      - closed
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to dockerhub
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build
      run: |
        docker build -t ${{secrets.DOCKER_USERNAME}}/eoscbot -f EOSC.Bot/Dockerfile .
        docker push ${{secrets.DOCKER_USERNAME}}/eoscbot:latest
  deploy: 
    needs: build
    runs-on: ec2_bot
    steps:
      - name: Prune unused images
        run: sudo docker system prune --force
      - name: Pull image from docker
        run: sudo docker pull ${{secrets.DOCKER_USERNAME}}/eoscbot:latest
      - name: Delete old container
        run: sudo docker rm -f eosc-bot-container
      - name: Run container
        run: sudo docker run -d -e Discord:Token=${{secrets.DISCORD_TOKEN}} -e api:endpoint=${{secrets.API_ENDPOINT}} -e bot:token="${{secrets.BOT_TOKEN}}" --name eosc-bot-container ${{secrets.DOCKER_USERNAME}}/eoscbot:latest