name: Deploy web

on:
  pull_request:
    types:
      - closed
    branches: 
      - main

jobs:
  build_web:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to dockerhub
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build
      run: |
        docker build -t ${{secrets.DOCKER_USERNAME}}/eoscweb -f EOSC.Web/Dockerfile .
        docker push ${{secrets.DOCKER_USERNAME}}/eoscweb:latest
  deploy_api: 
    needs: build_web
    runs-on: ec2_web
    steps:
      - name: Prune unused images
        run: sudo docker system prune --force
      - name: Pull image from docker
        run: sudo docker pull ${{secrets.DOCKER_USERNAME}}/eoscweb:latest
      - name: Delete old container
        run: sudo docker rm -f eosc-api-container
      - name: Run container
        run: sudo docker run -d -p 80:8080 --name eosc-api-container ${{secrets.DOCKER_USERNAME}}/eoscweb:latest